version: '3'
services:
  mongo:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    # command: use admin
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - '3000:80'
  api:
    build:
      context: ./badreads-backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./badreads-backend:/app
    restart: always
    env_file:
      - ./badreads-backend/.env
    expose:
      - 4000
    ports: 
      - 4000:4000
    depends_on: 
      - mongo
  react:
    build:
      context: ./badreads-frontend
      dockerfile: Dockerfile
    depends_on: 
      - api
    volumes:
      - /app/node_modules
      - ./badreads-frontend:/app
    # ports: 
    #   - 3000:3000
    # expose:
    #   - 3000
    links:
      - api
    stdin_open: true