version: '3'
services:
  mongo:
    image: 'mongo:4.2.8'
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  nginx:
    restart: always
    image: kareemelkasaby/nodenginx:latest
    ports:
      - '3000:80'
  localhost:
    image: kareemelkasaby/badreads-backend:latest
    # volumes:
    #   - /app/node_modules
    #   - ./badreads-backend:/app
    restart: always
    env_file:
      - ./badreads-backend/.env
    expose:
      - 4000
    ports: 
      - 4000:4000
    depends_on: 
      - mongo
  react:
    image: kareemelkasaby/badreads-frontend:latest
    depends_on: 
      - localhost
    # volumes:
    #   - /app/node_modules
    #   - ./badreads-frontend:/app
    # hello coment
    links:
      - localhost
    stdin_open: true